import { StrictMode, useEffect, useMemo, useState, type ReactNode } from "react";
import { createRoot } from "react-dom/client";
import { api } from "./api/client";
import type { components } from "./api/generated";
import { Button } from "./components/ui/button";
import "./index.css";

type Exam = components["schemas"]["Exam"]; type Student = components["schemas"]["Student"]; type Session = components["schemas"]["Session"]; type Event = components["schemas"]["Event"];
type Tab = "exams" | "students" | "sessions" | "audit";

function App() {
  const [token, setToken] = useState(() => localStorage.getItem("byod.admin_token") || "");
  const [draftToken, setDraftToken] = useState(token); const [tab, setTab] = useState<Tab>("exams");
  const [exams, setExams] = useState<Exam[]>([]); const [selected, setSelected] = useState<Exam | null>(null);
  const [students, setStudents] = useState<Student[]>([]); const [sessions, setSessions] = useState<Session[]>([]); const [events, setEvents] = useState<Event[]>([]);
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [showExam, setShowExam] = useState(false); const [showStudent, setShowStudent] = useState(false);
  const [sessionEvents, setSessionEvents] = useState<Event[] | null>(null); const [sessionDetail, setSessionDetail] = useState<Session | null>(null);
  const saveToken = () => { localStorage.setItem("byod.admin_token", draftToken.trim()); setToken(draftToken.trim()); };
  const loadExams = async () => { setBusy(true); setError(""); const r = await api.GET("/admin/api/exams"); if (r.error) setError("无法加载数据，请确认管理员 token 和服务状态。"); else setExams((r.data || []) as Exam[]); setBusy(false); };
  useEffect(() => { if (token) void loadExams(); }, [token]);
  const removeStudent = async (subject: string) => { if (!selected || !confirm(`移除学生 ${subject}？`)) return; await api.DELETE("/admin/api/exams/{examId}/students/{subject}", { params: { path: { examId: selected.id, subject } } }); void loadExam(selected); };
  const toggleStudent = async (student: Student) => { if (!selected) return; await api.PUT("/admin/api/exams/{examId}/students/{subject}", { params: { path: { examId: selected.id, subject: student.subject } }, body: { display_name: student.display_name, enabled: !student.enabled } }); void loadExam(selected); };
  const loadExam = async (exam: Exam) => { setSelected(exam); setTab("students"); const r = await api.GET("/admin/api/exams/{examId}/students", { params: { path: { examId: exam.id } } }); if (!r.error) setStudents((r.data || []) as Student[]); };
  const loadSessions = async () => { const r = await api.GET("/admin/api/sessions"); if (!r.error) setSessions((r.data || []) as Session[]); };
  const loadEvents = async () => { const r = await api.GET("/admin/api/events"); if (!r.error) setEvents((r.data || []) as Event[]); };
  const openSession = async (session: Session) => { setSessionDetail(session); const r = await api.GET("/admin/api/sessions/{sessionId}/events", { params: { path: { sessionId: session.id } } }); setSessionEvents(r.error ? [] : (r.data || []) as Event[]); };
  const updateSession = async (session: Session, action: "suspend" | "resume") => { const r = await api.POST("/admin/api/sessions/{sessionId}", { params: { path: { sessionId: session.id } }, body: { action } }); if (!r.error) { const next = r.data as Session; setSessionDetail(next); setSessions((items) => items.map((item) => item.id === next.id ? next : item)); } };
  const removeExam = async (exam: Exam) => { if (!confirm(`删除考试 ${exam.id}？`)) return; await api.DELETE("/admin/api/exams/{examId}", { params: { path: { examId: exam.id } } }); if (selected?.id === exam.id) setSelected(null); void loadExams(); };
  useEffect(() => { if (tab === "sessions") void loadSessions(); if (tab === "audit") void loadEvents(); }, [tab, selected]);
  const online = useMemo(() => sessions.filter((s) => s.state === "active").length, [sessions]);
  if (!token) return <div className="flex min-h-screen items-center justify-center px-4"><div className="w-full max-w-md rounded-xl border bg-white p-8 shadow-sm"><p className="text-xs font-semibold uppercase tracking-widest text-indigo-600">BYOD SERVER</p><h1 className="mt-2 text-2xl font-semibold">管理员登录</h1><p className="mt-2 text-sm text-slate-500">输入部署时配置的管理员 token。</p><input className="mt-6 w-full rounded-md border px-3 py-2" type="password" value={draftToken} onChange={(e) => setDraftToken(e.target.value)} onKeyDown={(e) => e.key === "Enter" && saveToken()} /><Button className="mt-4 w-full" onClick={saveToken}>进入后台</Button></div></div>;
  return <div className="min-h-screen"><header className="border-b bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5"><div><p className="text-xs font-semibold uppercase tracking-widest text-indigo-600">BYOD SERVER</p><h1 className="text-2xl font-semibold">考试管理后台</h1></div><div className="flex gap-2"><Button variant="outline" onClick={() => { localStorage.removeItem("byod.admin_token"); setToken(""); }}>退出</Button><Button onClick={() => void loadExams()}>刷新</Button></div></div></header><main className="mx-auto max-w-7xl space-y-6 px-6 py-8"><div className="grid gap-4 md:grid-cols-3"><Metric label="考试总数" value={String(exams.length)} /><Metric label="进行中" value={String(exams.filter((e) => e.state === "active").length)} /><Metric label="在线 session" value={String(online)} /></div><nav className="flex gap-1 rounded-lg border bg-white p-1 shadow-sm">{([["exams","考试"],["students","学生名单"],["sessions","在线 session"],["audit","审计日志"]] as [Tab,string][]).map(([id,label]) => <button key={id} className={`rounded-md px-4 py-2 text-sm ${tab === id ? "bg-slate-900 text-white" : "hover:bg-slate-100"}`} onClick={() => setTab(id)}>{label}</button>)}</nav>{error && <p className="rounded-md bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}{tab === "exams" && <ExamTable exams={exams} selected={selected} onSelect={(e) => { setSelected(e); setShowExam(true); }} onStudents={(e) => void loadExam(e)} onDelete={(e) => void removeExam(e)} onNew={() => { setSelected(null); setShowExam(true); }} busy={busy} />}{tab === "students" && <StudentPanel exam={selected} students={students} onAdd={() => setShowStudent(true)} onRemove={removeStudent} onToggle={toggleStudent} onReload={() => selected && void loadExam(selected)} />}{tab === "sessions" && <SessionPanel sessions={sessions} onOpen={(s) => void openSession(s)} onReload={() => void loadSessions()} />}{tab === "audit" && <AuditPanel events={events} />}</main>{showExam && <ExamDialog exam={selected} onClose={() => setShowExam(false)} onSaved={() => { setShowExam(false); void loadExams(); }} />}{showStudent && selected && <StudentDialog examId={selected.id} onClose={() => setShowStudent(false)} onSaved={() => { setShowStudent(false); void loadExam(selected); }} />}{sessionDetail && <SessionDialog session={sessionDetail} events={sessionEvents || []} onAction={(action) => void updateSession(sessionDetail, action)} onClose={() => { setSessionDetail(null); setSessionEvents(null); }} />}</div>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-semibold">{value}</p></div>; }
function ExamTable({ exams, selected, onSelect, onStudents, onDelete, onNew, busy }: { exams: Exam[]; selected: Exam | null; onSelect: (e: Exam) => void; onStudents: (e: Exam) => void; onDelete: (e: Exam) => void; onNew: () => void; busy: boolean }) { return <section className="rounded-xl border bg-white shadow-sm"><div className="flex items-center justify-between border-b px-6 py-4"><div><h2 className="font-semibold">考试</h2><p className="text-sm text-slate-500">源站和考试状态均存储在数据库中。</p></div><Button onClick={onNew}>新建考试</Button></div>{busy ? <p className="px-6 py-8 text-sm text-slate-500">加载中…</p> : <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-6 py-3">考试 ID</th><th className="px-6 py-3">源站</th><th className="px-6 py-3">状态</th><th className="px-6 py-3">操作</th></tr></thead><tbody className="divide-y">{exams.map((e) => <tr key={e.id} className={selected?.id === e.id ? "bg-indigo-50/40" : ""}><td className="px-6 py-4 font-medium">{e.id}</td><td className="max-w-md truncate px-6 py-4 text-slate-600">{e.base_url}</td><td className="px-6 py-4"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs">{e.state}</span></td><td className="flex gap-1 px-6 py-3"><Button variant="ghost" onClick={() => onStudents(e)}>学生</Button><Button variant="ghost" onClick={() => onSelect(e)}>编辑</Button><Button variant="ghost" onClick={() => onDelete(e)}>删除</Button></td></tr>)}{!exams.length && <tr><td colSpan={4} className="px-6 py-10 text-center text-slate-500">暂无考试</td></tr>}</tbody></table></div>}</section>; }
function StudentPanel({ exam, students, onAdd, onRemove, onToggle, onReload }: { exam: Exam | null; students: Student[]; onAdd: () => void; onRemove: (subject: string) => void; onToggle: (student: Student) => void; onReload: () => void }) { if (!exam) return <Empty text="请先在考试页选择考试。" />; return <section className="rounded-xl border bg-white shadow-sm"><div className="flex items-center justify-between border-b px-6 py-4"><div><h2 className="font-semibold">{exam.id} · 学生名单</h2><p className="text-sm text-slate-500">只有启用的 subject 可以参加考试。</p></div><div className="flex gap-2"><Button variant="outline" onClick={onReload}>刷新</Button><Button onClick={onAdd}>添加学生</Button></div></div><ul className="divide-y">{students.map((s) => <li key={s.subject} className="flex items-center justify-between px-6 py-4"><div><p className="font-medium">{s.display_name || "未命名学生"}</p><p className="text-xs text-slate-500">{s.subject}</p></div><div className="flex items-center gap-3"><span className={`rounded-full px-2 py-1 text-xs ${s.enabled ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-500"}`}>{s.enabled ? "已启用" : "已禁用"}</span><Button variant="ghost" onClick={() => onToggle(s)}>{s.enabled ? "禁用" : "启用"}</Button><Button variant="ghost" onClick={() => onRemove(s.subject)}>移除</Button></div></li>)}{!students.length && <li className="px-6 py-10 text-center text-slate-500">暂无学生</li>}</ul></section>; }
function SessionPanel({ sessions, onOpen, onReload }: { sessions: Session[]; onOpen: (s: Session) => void; onReload: () => void }) { return <section className="rounded-xl border bg-white shadow-sm"><div className="flex items-center justify-between border-b px-6 py-4"><div><h2 className="font-semibold">在线 session</h2><p className="text-sm text-slate-500">查看状态和违规次数。</p></div><Button variant="outline" onClick={onReload}>刷新</Button></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-6 py-3">Session</th><th className="px-6 py-3">考试</th><th className="px-6 py-3">Subject</th><th className="px-6 py-3">状态</th><th className="px-6 py-3">违规</th></tr></thead><tbody className="divide-y">{sessions.map((s) => <tr key={s.id} className="cursor-pointer hover:bg-slate-50" onClick={() => onOpen(s)}><td className="px-6 py-4 font-mono text-xs">{s.id}</td><td className="px-6 py-4">{s.exam_id}</td><td className="px-6 py-4">{s.subject || "—"}</td><td className="px-6 py-4">{s.state}</td><td className="px-6 py-4">{s.violation_count ?? 0}</td></tr>)}{!sessions.length && <tr><td colSpan={5} className="px-6 py-10 text-center text-slate-500">暂无 session</td></tr>}</tbody></table></div></section>; }
function AuditPanel({ events }: { events: Event[] }) { return <section className="rounded-xl border bg-white shadow-sm"><div className="border-b px-6 py-4"><h2 className="font-semibold">审计日志</h2><p className="text-sm text-slate-500">最近 200 条事件。</p></div><ul className="divide-y">{events.map((e) => <li key={e.id} className="px-6 py-4"><div className="flex items-center justify-between"><span className="font-medium">{e.type}</span><span className="text-xs text-slate-500">{new Date((e.occurred_at as number) * 1000).toLocaleString()}</span></div><p className="mt-1 text-xs text-slate-500">{e.session_id} · {e.severity}{e.details ? ` · ${e.details}` : ""}</p></li>)}{!events.length && <li className="px-6 py-10 text-center text-slate-500">暂无事件</li>}</ul></section>; }
function Empty({ text }: { text: string }) { return <div className="rounded-xl border bg-white px-6 py-12 text-center text-slate-500">{text}</div>; }
function ExamDialog({ exam, onClose, onSaved }: { exam: Exam | null; onClose: () => void; onSaved: () => void }) { const [id,setId]=useState(exam?.id||"");const [base,setBase]=useState(exam?.base_url||"");const [state,setState]=useState<Exam["state"]>(exam?.state||"draft");const [starts,setStarts]=useState(exam?.starts_at ? exam.starts_at.slice(0,16) : "");const [ends,setEnds]=useState(exam?.ends_at ? exam.ends_at.slice(0,16) : "");const [policy,setPolicy]=useState(exam?.policy ? JSON.stringify(exam.policy,null,2) : "{}");const [error,setError]=useState("");const submit=async()=>{setError("");if(!id||!base){setError("考试 ID 和源站 URL 不能为空");return}let policyValue: Record<string,unknown>;try{policyValue=JSON.parse(policy)}catch{setError("策略必须是合法 JSON");return}const body={id,base_url:base,state,starts_at:starts ? new Date(starts).toISOString() : null,ends_at:ends ? new Date(ends).toISOString() : null,policy:policyValue};const r=exam?await api.PATCH("/admin/api/exams/{examId}",{params:{path:{examId:exam.id}},body}):await api.POST("/admin/api/exams",{body});if(r.error){setError("保存失败，请检查输入和服务日志。");return}onSaved()};return <Modal title={exam?"编辑考试":"新建考试"} onClose={onClose}><label>考试 ID<input value={id} disabled={!!exam} onChange={e=>setId(e.target.value)} /></label><label>源站 base URL<input value={base} onChange={e=>setBase(e.target.value)} placeholder="https://cs101.gbu.edu.cn" /></label><label>状态<select value={state} onChange={e=>setState(e.target.value as Exam["state"])}><option>draft</option><option>scheduled</option><option>active</option><option>ended</option></select></label><div className="grid grid-cols-2 gap-3"><label>开始时间<input type="datetime-local" value={starts} onChange={e=>setStarts(e.target.value)} /></label><label>结束时间<input type="datetime-local" value={ends} onChange={e=>setEnds(e.target.value)} /></label></div><label>策略 JSON<textarea className="mt-2 h-36 w-full rounded-md border p-2 font-mono text-xs" value={policy} onChange={e=>setPolicy(e.target.value)} /></label>{error&&<p className="text-sm text-red-600">{error}</p>}<div className="flex justify-end gap-2"><Button variant="outline" onClick={onClose}>取消</Button><Button onClick={()=>void submit()}>保存</Button></div></Modal>; }
function StudentDialog({ examId, onClose, onSaved }: { examId: string; onClose: () => void; onSaved: () => void }) { const [subject,setSubject]=useState("");const [name,setName]=useState("");const submit=async()=>{if(!subject)return;const r=await api.PUT("/admin/api/exams/{examId}/students/{subject}",{params:{path:{examId,subject}},body:{display_name:name,enabled:true}});if(!r.error)onSaved()};return <Modal title={`添加学生 · ${examId}`} onClose={onClose}><label>Subject<input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="oidc:user-123" /></label><label>显示名称<input value={name} onChange={e=>setName(e.target.value)} /></label><div className="flex justify-end gap-2"><Button variant="outline" onClick={onClose}>取消</Button><Button onClick={()=>void submit()}>添加</Button></div></Modal>; }
function SessionDialog({ session, events, onAction, onClose }: { session: Session; events: Event[]; onAction: (action: "suspend" | "resume") => void; onClose: () => void }) { return <Modal title="Session 详情" onClose={onClose}><dl className="grid grid-cols-2 gap-3 text-sm"><dt className="text-slate-500">ID</dt><dd className="font-mono text-xs">{session.id}</dd><dt className="text-slate-500">考试</dt><dd>{session.exam_id}</dd><dt className="text-slate-500">Subject</dt><dd>{session.subject || "—"}</dd><dt className="text-slate-500">状态</dt><dd>{session.state}</dd><dt className="text-slate-500">违规次数</dt><dd>{session.violation_count ?? 0}</dd></dl><div><h3 className="mb-2 font-medium">事件</h3><ul className="max-h-60 divide-y overflow-auto rounded border">{events.map(e => <li key={e.id} className="px-3 py-2 text-xs"><span className="font-medium">{e.type}</span><span className="ml-2 text-slate-500">{e.severity}</span>{e.details && <p className="text-slate-500">{e.details}</p>}</li>)}{!events.length && <li className="px-3 py-4 text-center text-slate-500">暂无事件</li>}</ul></div><div className="flex justify-end gap-2">{session.state === "suspended" && <Button variant="outline" onClick={() => onAction("resume")}>恢复</Button>}{session.state === "active" && <Button variant="outline" onClick={() => onAction("suspend")}>暂停</Button>}<Button onClick={onClose}>关闭</Button></div></Modal>; }
function Modal({ title, children, onClose }: { title: string; children: ReactNode; onClose: () => void }) { return <div className="fixed inset-0 z-10 flex items-center justify-center bg-slate-950/30 p-4"><div className="w-full max-w-lg rounded-xl border bg-white p-6 shadow-xl"><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-semibold">{title}</h2><button className="text-slate-400" onClick={onClose}>×</button></div><div className="space-y-4">{children}</div></div></div>; }
createRoot(document.getElementById("root")!).render(<StrictMode><App /></StrictMode>);
