apiVersion: v1
kind: Service
metadata:
  name: {{ include "byod-server.fullname" . }}-data
spec:
  type: ClusterIP
  selector:
    app: {{ include "byod-server.fullname" . }}-data
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8787
