apiVersion: v1
kind: Service
metadata:
  name: {{ include "byod-server.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "byod-server.fullname" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8787
    - name: tunnel
      port: {{ .Values.service.tunnelPort }}
      targetPort: 8788
