package main

// This small checked-in generator keeps the contract reproducible in offline
// builds. CI runs go generate and fails if the generated contract changes.
import (
	"crypto/sha256"
	"fmt"
	"os"
)

func main() {
	b, err := os.ReadFile("../../openapi.yaml")
	if err != nil {
		panic(err)
	}
	sum := fmt.Sprintf("%x", sha256.Sum256(b))
	out := fmt.Sprintf(`// Code generated by internal/admin/generator; DO NOT EDIT.
package admin

const OpenAPISpecSHA256 = %q
`, sum)
	if err := os.WriteFile("api.gen.go", []byte(out), 0644); err != nil {
		panic(err)
	}
}
