{{- if gt (int .Values.replicaCount) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "byod-middleware.fullname" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ include "byod-middleware.fullname" . }}
{{- end }}
