{{- if and (not .Values.policySecret.existingSecret) .Values.policySecret.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "byod-middleware.fullname" . }}
type: Opaque
stringData:
  {{ .Values.policySecret.key }}: {{ .Values.policySecret.value | quote }}
{{- end }}
