/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["beginUserLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logoutUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/browser/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["beginBrowserLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/exams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listExams"];
        put?: never;
        post: operations["createExam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/exams/{examId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        get: operations["getExam"];
        put?: never;
        post?: never;
        delete: operations["deleteExam"];
        options?: never;
        head?: never;
        patch: operations["updateExam"];
        trace?: never;
    };
    "/admin/api/exams/{examId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["publishExam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/exams/{examId}/students": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        get: operations["listExamStudents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/exams/{examId}/students/{subject}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
                subject: string;
            };
            cookie?: never;
        };
        get?: never;
        put: operations["addExamStudent"];
        post?: never;
        delete: operations["removeExamStudent"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listUsers"];
        put?: never;
        post: operations["inviteUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        get: operations["getUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateUser"];
        trace?: never;
    };
    "/admin/api/exams/{examId}/participants": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        get: operations["listExamParticipants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/exams/{examId}/participants/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
                userId: string;
            };
            cookie?: never;
        };
        get?: never;
        put: operations["setExamParticipant"];
        post?: never;
        delete: operations["removeExamParticipant"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/exams/{examId}/admins": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        get: operations["listExamAdmins"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/exams/{examId}/admins/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
                userId: string;
            };
            cookie?: never;
        };
        get?: never;
        put: operations["setExamAdmin"];
        post?: never;
        delete: operations["removeExamAdmin"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/user-audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listUserAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/exams/{examId}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        get: operations["listExamSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        get: operations["getSession"];
        put?: never;
        post: operations["updateSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/sessions/{sessionId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        get: operations["listSessionEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{sessionId}/tunnel-ticket": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["issueTunnelTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exams/available": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAvailableExams"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        get: operations["getBrowserSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{sessionId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        get: operations["getBrowserSessionEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{sessionId}/violations": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reportViolation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exams/{examId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["completeExam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{sessionId}/start": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{sessionId}/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["heartbeatSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{sessionId}/end": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["endSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.yaml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOpenAPI"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Exam: {
            id: string;
            /** Format: uri */
            base_url: string;
            /** @enum {string} */
            state: "draft" | "scheduled" | "active" | "ended";
            /** Format: date-time */
            starts_at?: string | null;
            /** Format: date-time */
            ends_at?: string | null;
            policy?: {
                [key: string]: unknown;
            };
        };
        ExamInput: {
            id: string;
            /** Format: uri */
            base_url: string;
            /** @enum {string} */
            state?: "draft" | "scheduled" | "active" | "ended";
            /** Format: date-time */
            starts_at?: string | null;
            /** Format: date-time */
            ends_at?: string | null;
            policy?: {
                [key: string]: unknown;
            };
        };
        AvailableExam: {
            id: string;
            /** Format: uri */
            base_url: string;
            /** @enum {string} */
            state: "draft" | "scheduled" | "active" | "ended";
            /** Format: date-time */
            starts_at?: string | null;
            /** Format: date-time */
            ends_at?: string | null;
            completed: boolean;
        };
        SessionInput: {
            exam_id: string;
            /** Format: uri */
            return_uri?: string;
        };
        SessionBootstrap: {
            session_id: string;
            attempt_id: string;
            browser_session_id: string;
            browser_token: string;
            /** Format: uri */
            authorization_url: string;
            state: string;
        };
        BrowserSession: {
            session_id: string;
            exam_id: string;
            state: string;
            subject?: boolean;
            violation_count?: number;
            last_violation?: string;
            /** Format: int64 */
            last_seen_at?: number;
        };
        ViolationInput: {
            type: string;
            details?: string;
        };
        Student: {
            subject: string;
            display_name?: string;
            enabled: boolean;
        };
        StudentInput: {
            display_name?: string;
            enabled?: boolean;
        };
        User: {
            id: string;
            issuer: string;
            subject?: string | null;
            /** Format: email */
            email?: string | null;
            display_name: string;
            /**
             * @deprecated
             * @description Compatibility projection; use platform_admin and exam-admin memberships.
             * @enum {string}
             */
            role: "student" | "admin";
            platform_admin: boolean;
            enabled: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_login_at?: string | null;
        };
        UserInput: {
            /** Format: email */
            email: string;
            display_name?: string;
            platform_admin?: boolean;
            /**
             * @deprecated
             * @enum {string}
             */
            role?: "student" | "admin";
        };
        UserUpdate: {
            display_name?: string;
            platform_admin?: boolean;
            /**
             * @deprecated
             * @enum {string}
             */
            role?: "student" | "admin";
            enabled?: boolean;
        };
        ExamAdmin: {
            user: components["schemas"]["User"];
            enabled: boolean;
            /** Format: date-time */
            created_at: string;
        };
        Participant: {
            user: components["schemas"]["User"];
            enabled: boolean;
        };
        ParticipantInput: {
            enabled?: boolean;
        };
        UserAudit: {
            id: number;
            actor_id: string;
            user_id: string;
            action: string;
            details?: string;
            /** Format: date-time */
            occurred_at: string;
        };
        AuthMe: {
            user: components["schemas"]["User"];
            csrf_token: string;
            capabilities: {
                platform_admin: boolean;
                exam_admin: boolean;
            };
        };
        Session: {
            id: string;
            exam_id: string;
            subject: string;
            state: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_seen_at?: string;
            violation_count?: number;
        };
        SessionAction: {
            /** @enum {string} */
            action: "suspend" | "resume";
        };
        Event: {
            id: string;
            session_id: string;
            attempt_id?: string;
            browser_session_id?: string;
            type: string;
            severity: string;
            details?: string;
            /** Format: int64 */
            occurred_at: number;
        };
        TunnelTicket: {
            ticket: string;
            endpoint_id: string;
            /** Format: date-time */
            expires_at: string;
            /** @enum {string} */
            protocol: "byod-tunnel-v1";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    beginUserLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to OIDC authorization endpoint */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMe"];
                };
            };
            /** @description Login required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logoutUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    beginBrowserLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to the configured OIDC authorization endpoint */
            302: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listExams: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exams */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exam"][];
                };
            };
        };
    };
    createExam: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExamInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exam"];
                };
            };
        };
    };
    getExam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exam */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exam"];
                };
            };
        };
    };
    deleteExam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateExam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExamInput"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exam"];
                };
            };
        };
    };
    publishExam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Published */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exam"];
                };
            };
            /** @description Invalid publication state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listExamStudents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Students */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Student"][];
                };
            };
        };
    };
    addExamStudent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
                subject: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["StudentInput"];
            };
        };
        responses: {
            /** @description Added */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    removeExamStudent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
                subject: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listUsers: {
        parameters: {
            query?: {
                q?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
        };
    };
    inviteUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserInput"];
            };
        };
        responses: {
            /** @description Invited user */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Updated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    listExamParticipants: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Participants */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Participant"][];
                };
            };
        };
    };
    setExamParticipant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ParticipantInput"];
            };
        };
        responses: {
            /** @description Updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    removeExamParticipant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listExamAdmins: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exam administrators */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamAdmin"][];
                };
            };
        };
    };
    setExamAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ParticipantInput"];
            };
        };
        responses: {
            /** @description Updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    removeExamAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listUserAudit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User audit events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserAudit"][];
                };
            };
        };
    };
    listExamSessions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"][];
                };
            };
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
        };
    };
    updateSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionAction"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"][];
                };
            };
        };
    };
    listSessionEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"][];
                };
            };
        };
    };
    listEvents: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"][];
                };
            };
        };
    };
    issueTunnelTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exam-window tunnel ticket (reusable by HTTP CONNECT during its TTL; binary preface is single-use; revoked when the session is suspended or ended) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TunnelTicket"];
                };
            };
            /** @description Session is not active */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listAvailableExams: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exams assigned to the authenticated student */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailableExam"][];
                };
            };
            /** @description Login required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionInput"];
            };
        };
        responses: {
            /** @description Pending authenticated session */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionBootstrap"];
                };
            };
            /** @description Exam is not available */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Exam ended */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getBrowserSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Browser session state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrowserSession"];
                };
            };
            /** @description Exam ended */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getBrowserSessionEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"][];
                };
            };
        };
    };
    reportViolation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ViolationInput"];
            };
        };
        responses: {
            /** @description Violation recorded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    completeExam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Already completed or ended */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    startSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Started */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated or not started */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Exam ended */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    heartbeatSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Heartbeat accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Exam ended */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    endSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ended */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Already completed */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getOpenAPI: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAPI document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/yaml": string;
                };
            };
        };
    };
}
