/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/api/exams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listExams"];
        put?: never;
        post: operations["createExam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/exams/{examId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        get: operations["getExam"];
        put?: never;
        post?: never;
        delete: operations["deleteExam"];
        options?: never;
        head?: never;
        patch: operations["updateExam"];
        trace?: never;
    };
    "/admin/api/exams/{examId}/students": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        get: operations["listExamStudents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/exams/{examId}/students/{subject}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
                subject: string;
            };
            cookie?: never;
        };
        get?: never;
        put: operations["addExamStudent"];
        post?: never;
        delete: operations["removeExamStudent"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/exams/{examId}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        get: operations["listExamSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/sessions/{sessionId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        get: operations["listSessionEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.yaml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOpenAPI"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Exam: {
            id: string;
            /** Format: uri */
            base_url: string;
            /** @enum {string} */
            state: "draft" | "scheduled" | "active" | "ended";
            /** Format: date-time */
            starts_at?: string | null;
            /** Format: date-time */
            ends_at?: string | null;
        };
        ExamInput: {
            id: string;
            /** Format: uri */
            base_url: string;
            /** @enum {string} */
            state?: "draft" | "scheduled" | "active" | "ended";
            /** Format: date-time */
            starts_at?: string | null;
            /** Format: date-time */
            ends_at?: string | null;
        };
        Student: {
            subject: string;
            display_name?: string;
            enabled: boolean;
        };
        Session: {
            id: string;
            exam_id: string;
            subject: string;
            state: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_seen_at?: string;
            violation_count?: number;
        };
        Event: {
            id: string;
            type: string;
            severity: string;
            details?: string;
            /** Format: date-time */
            occurred_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listExams: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exams */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exam"][];
                };
            };
        };
    };
    createExam: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExamInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exam"];
                };
            };
        };
    };
    getExam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exam */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exam"];
                };
            };
        };
    };
    deleteExam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateExam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExamInput"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exam"];
                };
            };
        };
    };
    listExamStudents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Students */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Student"][];
                };
            };
        };
    };
    addExamStudent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
                subject: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Added */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    removeExamStudent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
                subject: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listExamSessions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"][];
                };
            };
        };
    };
    listSessionEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"][];
                };
            };
        };
    };
    getOpenAPI: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAPI document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/yaml": string;
                };
            };
        };
    };
}
